apiVersion: v1
kind: Service
metadata:
  name: api-customers
  labels:
    app: api-customers
    runtime: dotnet
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.apiCustomers.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: api-customers
