apiVersion: v1
kind: Service
metadata:
  name: api-bills
  labels:
    app: api-bills
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.apiBills.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: api-bills
