apiVersion: v1
kind: Service
metadata:
  name: api-raiders
  labels:
    app: api-raiders
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.apiRaiders.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: api-raiders
