apiVersion: v1
kind: Service
metadata:
  name: api-bills
  labels:
    app: api-bills
    app.kubernetes.io/name: api-bills
    app.kubernetes.io/instance: api-bills
    app.kubernetes.io/part-of: {{ include "nfl-wallet.partOf" . }}
    runtime: dotnet
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.apiBills.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: api-bills
