{{- if .Values.authorizationPolicy.enabled }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: api-customers-require-apikey
  labels:
    app: api-customers
spec:
  selector:
    matchLabels:
      app: api-customers
  action: ALLOW
  rules:
    - when:
        - key: request.headers[x-api-key]
          values: ["*"]
{{- end }}
