{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nfl-wallet-webapp
  labels:
    app: webapp
    app.kubernetes.io/component: httproute
spec:
  parentRefs:
    - name: {{ .Values.gateway.existingGatewayName | default "nfl-wallet-gateway" }}
  {{- with .Values.gateway.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: webapp
          port: {{ .Values.webapp.service.port }}
{{- end }}
