{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nfl-wallet-api-raiders
  labels:
    app: api-raiders
    app.kubernetes.io/component: httproute
spec:
  parentRefs:
    - name: {{ .Values.gateway.existingGatewayName | default "nfl-wallet-gateway" }}
  {{- with .Values.gateway.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api-raiders
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /api
      backendRefs:
        - name: api-raiders
          port: {{ .Values.apiRaiders.service.port }}
{{- end }}
