apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
    app.kubernetes.io/name: webapp
    app.kubernetes.io/instance: webapp
    app.kubernetes.io/part-of: {{ include "nfl-wallet.partOf" . }}
    runtime: nodejs
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.webapp.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: webapp
